version : '3.4'

services:
  insta2wp:
    image: insta2wp
    container_name: insta2wp
    networks:
      - default
    environment:
      WOOCOMMERCE_URL: ''
      WOOCOMMERCE_CONSUMER_KEY: ''
      WOOCOMMERCE_CONSUMER_SECRET: ''
      WORDPRESS_URL: ''
      WORDPRESS_USERNAME: ''
      WORDPRESS_PASSWORD: ''
      INSTAGRAM_TOKEN: ''
    volumes:
    - /etc/localtime:/etc/localtime
networks:
  default:
    external:
      name: proxy

